server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: log-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  datasource:
    url: jdbc:clickhouse://clickhouse:8123/default
    username: default
    password:
    driver-class-name: ru.yandex.clickhouse.ClickHouseDriver

logging:
  level:
    root: INFO
    com.example: DEBUG
